package com.dat.wordgame.common;


public enum MessageType {
// Session & lobby
LOGIN_REQ, LOGIN_OK, LOGIN_FAIL,
REGISTER_REQ, REGISTER_OK, REGISTER_FAIL,
LOBBY_SNAPSHOT, PLAYER_LIST, LEADERBOARD,
INVITE_SEND, INVITE_RECEIVE, INVITE_ACCEPT, INVITE_REJECT,

// Friend system
FRIEND_REQUEST_SEND, FRIEND_REQUEST_RECEIVE, FRIEND_REQUEST_ACCEPT, FRIEND_REQUEST_REJECT,
FRIEND_LIST_REQ, FRIEND_LIST_RESP, FRIEND_INVITE_SEND, FRIEND_INVITE_RECEIVE, FRIEND_INVITE_ACCEPT, FRIEND_INVITE_RESP,


// Room/game lifecycle
ROOM_CREATE, ROOM_CREATED, ROOM_JOINED, ROOM_STATE, GAME_START,
ROUND_START, ROUND_TICK, ROUND_END, GAME_END,


// Gameplay & chat
GUESS_SUBMIT, GUESS_UPDATE, CHAT, SURRENDER,


// Errors
ERROR
}