package com.dat.wordgame.common;


public enum MessageType {
// Session & lobby
LOGIN_REQ, LOGIN_OK, LOGIN_FAIL,
REGISTER_REQ, REGISTER_OK, REGISTER_FAIL,
LOBBY_SNAPSHOT, PLAYER_LIST, LEADERBOARD,
INVITE_SEND, INVITE_RECEIVE, INVITE_ACCEPT, INVITE_REJECT,

// Friend system
FRIEND_REQUEST_SEND, FRIEND_REQUEST_RECEIVE, FRIEND_REQUEST_ACCEPT, FRIEND_REQUEST_REJECT,
FRIEND_LIST_REQ, FRIEND_LIST_RESP, FRIEND_INVITE_SEND, FRIEND_INVITE_RESP,
USER_SEARCH_REQ, USER_SEARCH_RESP,

// Room invite system (different from challenge invite)
ROOM_INVITE_SEND, ROOM_INVITE_RECEIVE, ROOM_INVITE_RESP, ROOM_INVITE_ACCEPT, ROOM_INVITE_REJECT,


// Room/game lifecycle
ROOM_CREATED, ROOM_JOINED, ROOM_STATE, ROOM_LEFT,
ROUND_START, ROUND_TICK, ROUND_END, GAME_END,


// Gameplay & chat
GUESS_SUBMIT, GUESS_UPDATE, CHAT, SURRENDER,


// Errors
ERROR
}